### ISSUE TITLE
headless pairing ?

### ISSUE THREAD

**Issue by mczerski** [hadess/CHIP-bluetooth-speaker#12]
Hi,

Do this project support headless pairing ? I mean that there is no need for any interaction with the CHIP to accept pairing from the phone. I can't get it to work in this manner and after reading the agent-helper.c code I believe that there is no such possibility.
If I run the bt-agent like that:
sudo ./bt-agent -c NoInputNoOutput -p bluetooth-default-pin
I always get the request for confirmation (yes or no). in agent-helper.c in _bt_agent_method_call_func function in if branch that corresponds to "RequestAuthorization" method_name (line 182) there is no other way to authorize the pairing. And after reading this http://www.bluez.org/bluez-5-api-introduction-and-porting-guide/, in "The new AgentManager1 interface" there is stated that "RequestAuthorization" is called if there is pairing request that does no require any action for the user.

**Comment by hadess** [comment]
What device are you trying to connect from? When using my phone, or a recent Linux distribution, it should try the '0000' pin code straight away, rather than a Bluetooth 4.0 type pairing like the one you've seen above where you need to match codes on both sides.

**Comment by hadess** [comment]
No reply for a while, closing.
