### ISSUE TITLE
binary file checksum

### ISSUE THREAD

**Issue by nonbinary** [hadess/CHIP-bluetooth-speaker#13]
I can't find a way to verify the integrity of the binary file. As the source code isn't present here, I have no way of inspecting it. Was it copied from somewhere where I could look at the source code and verify the checksums?

**Comment by hadess** [comment]
Good point. I added a link to the sources (my branch, as the upstream is pretty crashy). The PR for fixing upstream is at https://github.com/khvzak/bluez-tools/pull/9 if you want to follow.

**Comment by nonbinary** [comment]
Fantastic, thank you!

**Comment by hadess** [comment]
And I also noticed that the explanation was already in the commit message for the file :)
https://github.com/hadess/CHIP-bluetooth-speaker/commit/713d380a561f49bd28b6966540e056534e796bea
