### ISSUE TITLE
Why is it necessary to change passwords?

### ISSUE THREAD

**Issue by petabite** [hadess/CHIP-bluetooth-speaker#18]
Hi,

I have a question. Why is it necessary to change the root and chip passwords after installation?

**Comment by hadess** [comment]
Because they're the default ones, and thus anyone can guess them.

**Comment by petabite** [comment]
But i mean why would that matter if people knew the password.

**Comment by hadess** [comment]
Because they could log in to your CHIP, and do whatever they want with it.

**Comment by petabite** [comment]
Ah. I see. So it has nothing to do with the bluetooth service running or anything. Thanks.
