### ISSUE TITLE
Multiple Bluetooth sources?

### ISSUE THREAD

**Issue by satmandu** [hadess/CHIP-bluetooth-speaker#19]
I'm trying to figure out a way to get two android devices to send audio simultaneously via bt to a bt sink/speaker. (Dedicated waze device + phone -> vehicle via chip.)

I know that pulseaudio can monitor multiple inputs... but can the bluetooth hardware/stack support multiple simultaneous inputs?

**Comment by hadess** [comment]
I'm pretty certain that the code, and older versions of the standard, only support one audio device at a time. You might want to bring this problem to the bluez list instead.
