### ISSUE TITLE
Popping and skipping with NTC Kernel 4.4 Headless

### ISSUE THREAD

**Issue by byteporter** [hadess/CHIP-bluetooth-speaker#21]
I expect this happens on all the 4.4 images, but this is the one I've tried. Looks like they added a service called ubihealthd to monitor the life of the internal NAND, but it causes skipping in audio. I first noticed it by tailing /var/log/daemon.log and seeing the writes from that service's logged corresponding with the skips I was hearing. With a little searching, I found this thread regarding the issue on the NTC forum:

https://bbs.nextthing.co/t/alsa-causing-stutter-hanging-in-pico-8-mednafen-retroarch-arm-solved-maybe-please-help-us-test-verify/13765/117

And I can confirm that simply disabling the service fixes the issue for me, however I'm not sure how important this service is for the life of the NAND so maybe this should be open to find a better fix? Sounds like it's an issue with ubihealthd though and not these scripts. Still, putting it here in case it helps someone else.

**Comment by hadess** [comment]
I'll use this bug as a reminder to add a warning in the script when `ubihealthd` is enabled, thanks.

**Comment by hadess** [comment]
Can you take a look at the "hardware" section of the README? I had problems with this when plugging my CHIP directly in my computer. Using a large battery or a discrete power supply worked for me.

Didn't have problems with ubihealthd, from what I can tell.

**Comment by byteporter** [comment]
I'm almost positive I had it plugged into the wall with an old Asus charger from my original Nexus tablet or a battery when I was playing with this. Sounds like you're describing more noise in the signal itself from a dirty power source? It definitely would skip slightly before I disabled ubihealthd. From checking what's been going on in that linked ALSA/Pico8 thread, people there have been ditching systemd and going back to sysvinit to fix it, though some seem to have had success cranking the nice level of the system services up to nearly max and turning the nice for Pico8 way low. Someone even linked a fork of Debian that uses sysvinit instead, although I know now we're heading toward religious war territory :)

I do know that disabling the ubihealthd service fixed it for me and I didn't really mess with it since. I don't use it very often so I can't say what that means for the health of the ubifs long term, I haven't had issues yet but mine just stays powered on for the most part.

But definitely a good idea to use a clean power source when dealing with audio regardless.

**Comment by byteporter** [comment]
Welp, I reset my device today and it now kernel panics because the storage is corrupt, so I guess ubihealthd is important, lol

There's a good chance I won't ever look at it again as I have a really nice commercial bluetooth speaker now, but maybe it's another useful data point for someone.

**Comment by hadess** [comment]
Fair enough. I'll close this then, and we'll create a new issue if somebody sees it again. Thanks!
