### ISSUE TITLE
Volume control doesn't work

### ISSUE THREAD

**Issue by hadess** [hadess/CHIP-bluetooth-speaker#8]
When using the iOS volume control, the volume doesn't actually change.

**Comment by teuteuguy** [comment]
Has someone figured out how to fix this ?

**Comment by hadess** [comment]
Nope, otherwise I'd have fixed it already ;)

I'm guessing that some events don't get through from bluez to PulseAudio.

**Comment by teuteuguy** [comment]
Anything we can do to help test / fix ?

**Comment by hadess** [comment]
Figure out if something is being sent to bluez, and if so, why it's not being forwarded to PulseAudio.

**Comment by bafoed** [comment]
I've just fixed the problem by upgrading to latest bluez version (5.43-1 at this moment)  and modifying bluetooth.service. 

## Step 1. Upgrading BlueZ 
Run: 
```
apt-get update
apt-get install bluez-tools pulseaudio-module-bluetooth
``` 
and continue to **Step 2**.

Several users have reported that this is not necessary, but if you want to upgrade BlueZ to testing (unstable) version, use this instructions:
<details>
<summary>Upgrading BlueZ to testing (unstable) version</summary>


Create **`/etc/apt/apt.conf.d/99defaultrelease`** with contents:
```
APT::Default-Release "stable";
```

Create **`/etc/apt/sources.list.d/testing.list`** with urls for testing / unstable sources:
```
deb     http://ftp.de.debian.org/debian/    testing main contrib non-free
deb-src http://ftp.de.debian.org/debian/    testing main contrib non-free
deb     http://security.debian.org/         testing/updates  main contrib non-free
```
run
```
apt-get update
```
and then upgrade pulseaudio and bluez packages with:
```
apt-get -t testing install bluez-tools pulseaudio-module-bluetooth
```
I did not agree to replace the configuration files during the installation, the current configuration works on the new version without any changes.

Reboot your chip and see if pulseaudio worked right.
</details>

## Step 2. Edit bluetooth.service
Run
```
nano /lib/systemd/system/bluetooth.service
```
and add **--plugin=a2dp** as an argument to **bluetoothd**,  like
```
ExecStart=/usr/lib/bluetooth/bluetoothd --plugin=a2dp
```
Run
```
systemctl daemon-reload
systemctl restart bluetooth
```
to apply changes. Now volume control from bluetooth devices should work (tested on iPhone iOS 10.0).

## Troubleshooting
If you couldn't connect to CHIP after upgrading, verify that bluetooth adapter is powered on:
Run **`bt-adapter --info`**.
If you see **Powered: 0**, you can re-enable it using **`bt-adapter --set Powered 1`**.

**Comment by hadess** [comment]
Very useful, thanks. Would be useful if you could figure out which version of BlueZ, or even which change, brought this functionality.

**Comment by bafoed** [comment]
I found this commit: https://github.com/r10r/bluez/commit/a614d65cacab8eefd8c2d8f995aed481e375ba42
According to it's date, I can assume that the error has been fixed since version 5.8 (released 08 Aug 2013).

**Comment by hadess** [comment]
That's not the upstream version of bluez, and that patch doesn't look like it's upstream either.
This however is more recent and might be it:
https://git.kernel.org/cgit/bluetooth/bluez.git/log/profiles/audio/avrcp.c
Look for the 3 patches from 2015-09-15 that mention volume. Which would mean it was fixed in bluez 5.15. Which version is on the default CHIP install again?

**Comment by bafoed** [comment]
I can not say exactly what version of bluez used in the base image, but after a standard upgrade (apt-get update && apt-get upgrade) it must be updated to version from stable (jessie) repository, ie 5.23-2. 
Good remark, it is quite possible that the upgrade to the unstable version is not required.

**Comment by mph070770** [comment]
I implemented these changes to get iOS volume working - great.

Now, it is possible to add buttons to CHIP to implement local volume control that will be mirrored on the iOS device?

**Comment by petabite** [comment]
Hi @mph070770,

When you did this, did you have problems with the Bluetooth service starting up at boot of CHIP?

**Comment by mph070770** [comment]
Hi @BugsForDays , no problems with startup. I'm using 4.4 kernel and the BT starts and advertises as expected on boot up. 
It looks like I need to use dbus calls to change the volume of bluez. I'm trying to get to the bottom of that now.

**Comment by petabite** [comment]
Alright. Sounds good.

**Comment by patriot1889** [comment]
Has anyone been using DBus to control the bluetooth device? For example skipping tracks etc?

example: "dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX/player0 org.bluez.MediaPlayer1.Next"

I've found that if I use the "--plugin=a2dp" fix then I can no longer use MediaPlayer dbus controls.
Any thoughts?

PS. the "--plugin=a2dp" fix works perfectly fine on 5.23-2 for me, no need to update to a version not in Stable.

**Comment by bafoed** [comment]
Hi @adenbeckitt, 
as far as I know, you can't use the A2DP profile to control playback, you need AVRCP profile — it is the profile that is enabled by default (if there isn't argument **--plugin** on bluetoothd launch). The volume control is not implemented in AVRCP out of the box, but implemented in A2DP, that's why volume control works after switching to A2DP.
While using AVRCP, I noticed that /player interface has an signal (event) which triggers each time when something changes in playback, e.g. connected or playback state, track name and most importantly for us — volume change events. 
Here is it's definition :
`signal void org.freedesktop.DBus.Properties.PropertiesChanged(QString interface, QVariantMap changed_properties, QStringList invalidated_properties)`
I think that if we can start to listen to this signal, catch the volume change event and handle it correctly, there will be no need to use old A2DP profile.

**Comment by patriot1889** [comment]
Very interesting! Should be easy enough. I'll check it out when I get a moment :)

**Comment by patriot1889** [comment]
The code here will take the volume changes and apply it to an audio output;
https://github.com/adenbeckitt/Bluez-AVRCP-Volume-Control

I'm using a raspberry pi so I have hardcoded it to the third mixer control (3.5mm output)
Just change the command in the variable 'cmd' to perform any action you need.

Hope this works for you guys!
@bafoed

**Comment by hadess** [comment]
@adenbeckitt Nice! Any chance you could write a .service file for it as well, so it's started after bluez and PulseAudio have started?

I should also note that using dbus-glib is not recommended. You should use GDBus instead. See this example:
https://wiki.gnome.org/HowDoI/GDBusPython

I'll look into integrating that into the installer script.

**Comment by patriot1889** [comment]
I would just use something like this for a service;

```
[Unit]
Description=Volume Watcher

[Service]
User=root
Type=simple
ExecStart=/usr/local/bin/volume-watcher.py

[Install]
WantedBy=multi-user.target

```
Pop it in a file called '/etc/systemd/system/volume-watcher.service' or similar

Run
```
sudo systemctl enable volume-watcher.service
sudo systemctl start volume-watcher.service
```

I don't think you need to tell it to wait for bluez or pulse audio to start, works fine for me. :)

Also, I'll have a look at changing to GDBus at some point but I have more pressing things to deal with for my project at the moment :)
